name: Deploy-KRISE-eksisterende-image-RETT-I-PROD
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for imaget som skal ut. Kun tag, ikkje fullt namn'
        required: true
        type: string
env:
  IMAGE: ghcr.io/navikt/familie-ks-sak
jobs:
  deploy-to-prod:
    name: Deploy eksisterende image til dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/app-dev.yaml
          VAR: image=${{ env.IMAGE }}:${{ inputs.tag }}
